### ISSUE TITLE
Use the HAL I2S Driver

### ISSUE THREAD

**Issue by milewski** [10buttons/awedio_esp32#1]
Hi, now that `esp-idf-hal` has an I2S driver, couldn't the setup config be simplified? https://github.com/esp-rs/esp-idf-hal/blob/master/src/i2s.rs

**Comment by benhansen-io** [comment]
The i2s driver hasn't made it into a esp-idf-hal release yet but yes when it is released I'll look and see if it can replace the current direct usages in esp-idf-sys. I'll leave this ticket open until then. Thanks for the suggestion.

**Comment by milewski** [comment]
It looks like it has now been merged: https://github.com/esp-rs/esp-idf-hal/blob/master/CHANGELOG.md#0420---2023-10-17 :)

**Comment by benhansen-io** [comment]
Thanks for the reminder. I just pushed v0.3.0 which uses the new hal API. This version requires IDF v5. Let me know if you have any questions. I would love to hear if you end up building a project with the library.
